### ISSUE TITLE
Clarification Question: Removal from Radarr and 'prevent movie from being added to Radarr by lists'

### ISSUE THREAD

**Issue by michpas** [rfsbraz/deleterr#101]
Question.
When I manually delete a movie from Radarr, I get the option

- (Add list exclusion) Prevent movie from being added to Radarr by lists
- (Delet movie file) Delete the movie file and movie folder.

With this script, can I also set have the (add list exclusion) option? So that the movie is not immediately redownloaed when its part of a Radarr list?

**Comment by rfsbraz** [comment]
Hi! This makes alot of sense. I never added it because my workflow doesn't rely around radarr lists, so I overlooked it. I'll add the option to exclude on deletion and let you know

**Comment by rfsbraz** [comment]
This is avaiable in `v0.0.16`, give it a try! Check the PR for details on how to enable it.
