### ISSUE TITLE
Add arm64 image build to registry

### ISSUE THREAD

**Issue by nandi95** [rfsbraz/deleterr#114]
If using servarr on a rpi5 it won't be able to run deleterr due to the following:
```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Can this platform be added to the build process. This is an option on the `docker/build-push-action@v5`

**Comment by rfsbraz** [comment]
Hi! Can you please test with `ghcr.io/rfsbraz/deleterr:pr-120` and see if works for you? #120

**Comment by jeremy-green** [comment]
Hi there, I was having the same issue. I tested the image above and it works for me.

**Comment by rfsbraz** [comment]
Thanks @jeremy-green! Merged it
