### ISSUE TITLE
Writer/Producer Exclude on Sonarr Library causes crash

### ISSUE THREAD

**Issue by mlamoure** [rfsbraz/deleterr#22]
Once I add any value to writer, producer for the TV Library I experience a crash.

> deleterr  | Traceback (most recent call last):
deleterr  |   File "<frozen runpy>", line 198, in _run_module_as_main
deleterr  |   File "<frozen runpy>", line 88, in _run_code
deleterr  |   File "/app/app/deleterr.py", line 367, in <module>
deleterr  |     main()
deleterr  |   File "/app/app/deleterr.py", line 364, in main
deleterr  |     Deleterr()
deleterr  |   File "/app/app/deleterr.py", line 37, in __init__
deleterr  |     self.process_sonarr()
deleterr  |   File "/app/app/deleterr.py", line 95, in process_sonarr
deleterr  |     for sonarr_show in self.process_library_rules(library, plex_library, all_show_data, show_activity, trakt_items):
deleterr  |   File "/app/app/deleterr.py", line 249, in process_library_rules
deleterr  |     if not self.is_movie_actionable(library_config, activity_data, media_data, trakt_movies, plex_media_item, last_watched_threshold,                                                          added_at_threshold, apply_last_watch_threshold_to_collections):
deleterr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deleterr  |   File "/app/app/deleterr.py", line 305, in is_movie_actionable
deleterr  |     if producer.lower() in (g.tag.lower() for g in plex_media_item.producers):
deleterr  |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
deleterr  |   File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 516, in __getattribute__
deleterr  |     value = super(PlexPartialObject, self).__getattribute__(attr)
deleterr  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deleterr  | AttributeError: 'Show' object has no attribute 'producers'
deleterr exited with code 0

**Comment by rfsbraz** [comment]
Seems like I forgot to test all the properties with shows, fix incoming.

**Comment by rfsbraz** [comment]
@mlamoure should be fixed if you pull the latest master!
