### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by elit3ge** [rfsbraz/deleterr#35]
Filled out all the settings, however, I am shown this error.

![image](https://github.com/rfsbraz/deleterr/assets/1644699/5dbf1b32-80c7-4020-b992-4f86453422ac)

**Comment by rfsbraz** [comment]
Can you show me your settings please? Make sure to redact personal info.

**Comment by nicholasbackwell** [comment]
Same here. I got everything setup today and ran my first dry-run and it worked. I adjusted my action settings and tried another dry-run 20 minutes later and now I'm getting this error shared above. 

I'm editing files with VS code and running with WSL2 and Docker Desktop. I've tried deleting all containers and all extracted zip files, then I re-extracted the latest zip and filled out basic settings again but still getting the same result.

**Comment by nicholasbackwell** [comment]
Nevermind, I figured it out my setup.

It was in my library configuration the "last_watched_threahold=true" was causing my issue. 

I think in the stock settings it is enabled by default for the Movies library but not Shows/Anime library and that's how I ran the first dry-run. After I think I enabled for Shows and Anime which broke it for me.

**Comment by elit3ge** [comment]
Anything? @nicholasbackwell your error doesn't apply to me.

**Comment by nicholasbackwell** [comment]
Nothing to add from me sorry. I still can't get my setup out of dry-run mode and haven't had anymore time to look at it since. I'm working on setting up a new server with a Linux VM so at some point I'll try running it again on a true Linux Docker container and make another report back here but as far Windows I'm not sure what else I can try.

**Comment by rfsbraz** [comment]
> Nevermind, I figured it out for my setup
> 
> It was in my library configuration the "apply_last_watched_threahold_to_collections=true"
> 
> I think in the stock settings it is enabled by default for the Movies library but not Shows/Anime
> 
> I think I enabled for Shows and Anime which broke it for me. I turned it off for all 3 libraries for now and it seems to be logging properly for now
> 
> I attempted to run a live demo and perform 100 actions but it seems to be stuck in dry-run mode mode so I can't get it to actually delete anything

This is an obvious one but have you made sure the `dry_run: true` line is off of your settings.yaml?

**Comment by rfsbraz** [comment]
@elit3ge tried your settings and I'm running them fine. Added a log so you can make sure if the settings were picked up correctly in c045ecb75d770671c11ba0cf85e9cee32a23d02e
