### ISSUE TITLE
Does this work with Sonarr?

### ISSUE THREAD

**Issue by newadventure079** [rfsbraz/deleterr#98]
Sonarr is mentioned all over the main repo but at https://github.com/rfsbraz/deleterr/blob/develop/docs/CONFIGURATION.md it says **Sonarr [NOT IMPLEMENTED YET]**

**Comment by rfsbraz** [comment]
No, if the show matches your configuration the _entire_ show will be removed. So if you set a show to be deleted after being unwatched for 3 months, any play of any episode during that period will prevent it from being deleted. Like I said, more fine grain control over how a show is deleted (episode, season, show) will be added in the future.
